language: node_js
node_js:
   - "6.0.0"

branches:
  only:
    - master

notifications:
    email: true

addons:
  sauce_connect:
    username: "prateekbh"
  jwt:
    secure: "ewlrIcvQ+FplALbnZQgbwvtUB+JkahAiFzjxv3drMucmOmyseIRyot3uS2yNdeAcv2/boNjV70EFxp9g1DbxVv8cT2ySDefwmWl6iACcTlSlhglm58EQr30E7LLVEQ+9sQdd+OV/FRczWCcf6tZ9xmxvsrV61xW0mAJNCQtxDunRLtrS2YxP+d/3xWawb9w46cnnjgerk9iy7iGA0lsjg3eaLjrI7UClR2vjsiBFg8CNGGXtJzTsJZ9/INC5rFaLYXmT5OAg+4k8C9og+1RtG888Ke5LoYrnjDYGSeLVAtmqVCK6GAxqARSUrRcwBz5izXgiA3uWfJUqGIIKJ9a+o2GSkoNIX+KOcBrnVyvTwLJ2mEwCmHW4bp5JHxwL/6Zt285/E1gGywXeklL4v9198E+I+iL7+74KEToONxQHwOMmghn/Ik13Jgb2GlV0m7hakThJopv59K1g31WJxIM6Wg9Q3cA5ZrHGcPjF5awiNDI3mdamRhYT+h+j4QAmjweJaCik+8RQnsDTNRcQ8CIBBbd44DTixooS7VzLd5jaZsRnNOvvPpNH0oGX4dJIMe/TufJGSieVSseLu5ZtEwxz27Wpd+GFkGz8cLALEazaVBIJalo0YTAZVLFCsULJ81sBVTgzoQYBOqLlLdm1sUumgALGgUsdSht4Vj04uLZmwG8="