language: node_js
node_js:
   - "6.0.0"

branches:
  only:
    - master

notifications:
    email: true

addons:
  sauce_connect:
    username: "prateekbh"
    access_key: "cb330837-aa83-49fa-8e2c-5742005b26df"